/**
 * ComfyUI task executor — handles art/music/sfx tasks by submitting
 * ComfyUI workflows and downloading results to the project.
 *
 * Task description must specify:
 *   - workflow_template: filename in project's comfyui-workflows/ directory
 *   - params: JSON object mapping node IDs to input overrides
 *   - output_path: where to save the generated file in the project
 *
 * These are extracted from the task description by convention:
 *   [workflow: sprite_generator.json]
 *   [params: {"6": {"text": "pixel art fire symbol, 64x64"}}]
 *   [output: games/game1_clickonomicon/assets/sprites/symbol_fire.png]
 */

import { readFileSync, existsSync } from "fs";
import { resolve } from "path";
import { spawnSync } from "child_process";
import type { Db, Machine, Project, ForemanTask } from "../db";
import { executeComfyUIWorkflow, buildWorkflowFromTemplate } from "./comfyui";
import { buildWorkflow, PRESETS, type PresetName } from "./comfyui-workflows";
import { getBreaker } from "./circuit-breaker";
import { nudgeDirector } from "../director/scheduler";
import { registerActiveTask, unregisterActiveTask } from "./executor";

/**
 * Execute a ComfyUI generation task.
 * Parses workflow template + params from task description,
 * submits to ComfyUI, downloads output to the project.
 */
export async function executeComfyUITask(
  ctx: { db: Db },
  machine: Machine,
  task: ForemanTask,
  project: Project,
): Promise<void> {
  const { db } = ctx;
  const breaker = getBreaker(machine.id);

  const foremanRun = db.createForemanRun({
    task_id: task.id,
    machine_id: machine.id,
    attempt: task.retry_count + 1,
    model_id: "comfyui",
  });

  db.updateForemanTask(task.id, {
    status: "running",
    machine_id: machine.id,
    resolved_model: "comfyui",
    started_at: new Date().toISOString(),
  });

  db.updateForemanRun(foremanRun.id, {
    status: "running",
    started_at: new Date().toISOString(),
  });

  const startTime = Date.now();
  const controller = new AbortController();
  registerActiveTask(task.id, controller);

  try {
    // Parse workflow info from task description
    const workflowFile = extractTag(task.description, "workflow");
    const presetName = extractTag(task.description, "preset");
    const promptText = extractTag(task.description, "prompt");
    const paramsStr = extractTag(task.description, "params");
    const outputPath = extractTag(task.description, "output");

    if (!outputPath) {
      throw new Error("ComfyUI task missing [output: ...] tag in description");
    }

    let workflow: Record<string, unknown>;

    if (presetName) {
      // Preset-based workflow generation (no template files needed)
      const preset = PRESETS[presetName as PresetName];
      if (!preset) {
        throw new Error(`Unknown ComfyUI preset: "${presetName}". Available: ${Object.keys(PRESETS).join(", ")}`);
      }
      if (!promptText) {
        throw new Error("ComfyUI task with [preset:] must also have a [prompt:] tag");
      }
      workflow = buildWorkflow({ ...preset, prompt: promptText });
    } else if (workflowFile) {
      // Template-based workflow (load from project's comfyui-workflows/)
      const templatePath = resolve(project.workdir, "comfyui-workflows", workflowFile);
      if (!existsSync(templatePath)) {
        throw new Error(`Workflow template not found: ${templatePath}`);
      }
      const template = JSON.parse(readFileSync(templatePath, "utf-8"));
      const params = paramsStr ? JSON.parse(paramsStr) : {};
      workflow = buildWorkflowFromTemplate(template, params);
    } else {
      throw new Error("ComfyUI task must have either [preset: ...] or [workflow: ...] tag in description");
    }

    // Output to a temp directory, then copy to the right place
    const outputDir = resolve(project.workdir, ".comfyui-output");

    // Execute
    const result = await executeComfyUIWorkflow(
      machine.base_url,
      workflow,
      outputDir,
      controller.signal,
    );

    const durationMs = Date.now() - startTime;
    breaker.recordSuccess();

    if (result.outputFiles.length === 0) {
      throw new Error("ComfyUI workflow produced no output files");
    }

    // Copy the first output file to the target path
    const targetPath = resolve(project.workdir, outputPath);
    const { mkdirSync, copyFileSync } = await import("fs");
    const { dirname } = await import("path");
    mkdirSync(dirname(targetPath), { recursive: true });
    copyFileSync(result.outputFiles[0].localPath, targetPath);

    // Git add the new file
    if (existsSync(resolve(project.workdir, ".git"))) {
      spawnSync("git", ["add", outputPath], { cwd: project.workdir });
      spawnSync("git", ["commit", "-m", `[Foreman] ${task.title}\n\nGenerated by ComfyUI`], { cwd: project.workdir });
    }

    db.updateForemanRun(foremanRun.id, {
      status: "pass",
      output: JSON.stringify([{
        step: 1,
        text: `Generated ${result.outputFiles.length} file(s): ${result.outputFiles.map(f => f.filename).join(", ")}`,
        tokens: { prompt: 0, completion: 0 },
        durationMs,
      }]),
      completed_at: new Date().toISOString(),
      duration_ms: durationMs,
    });

    db.updateForemanTask(task.id, {
      status: "awaiting_review",
      completed_at: new Date().toISOString(),
      duration_ms: durationMs,
    });

    if (task.directive_id) nudgeDirector(db);

  } catch (err) {
    const durationMs = Date.now() - startTime;
    const errorMsg = err instanceof Error ? err.message : String(err);
    breaker.recordFailure();

    db.updateForemanRun(foremanRun.id, {
      status: "fail",
      error_message: errorMsg.slice(0, 5000),
      completed_at: new Date().toISOString(),
      duration_ms: durationMs,
    });

    const newRetryCount = task.retry_count + 1;
    if (newRetryCount < task.max_retries) {
      const backoffMs = Math.pow(2, newRetryCount) * 30_000;
      db.updateForemanTask(task.id, {
        status: "queued",
        retry_count: newRetryCount,
        next_retry_at: new Date(Date.now() + backoffMs).toISOString(),
        error_message: errorMsg.slice(0, 5000),
        machine_id: null,
        duration_ms: durationMs,
      });
    } else {
      db.updateForemanTask(task.id, {
        status: "failed",
        retry_count: newRetryCount,
        error_message: errorMsg.slice(0, 5000),
        machine_id: null,
        duration_ms: durationMs,
        completed_at: new Date().toISOString(),
      });
    }

    if (task.directive_id) nudgeDirector(db);
  } finally {
    unregisterActiveTask(task.id);
  }
}

/** Extract a [tag: value] from task description */
function extractTag(description: string, tag: string): string | null {
  const match = description.match(new RegExp(`\\[${tag}:\\s*(.+?)\\]`, "i"));
  return match ? match[1].trim() : null;
}
